/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module asel_19 (
    input [15:0] ra_data,
    input asel,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    out = 1'h0;
    if (asel == 1'h0) begin
      out = ra_data;
    end else begin
      out = 16'h0001;
    end
  end
endmodule
