/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input usb_rx,
    output reg usb_tx,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip,
    output reg red0,
    output reg green0,
    output reg blue0,
    output reg red1,
    output reg green1,
    output reg blue1,
    output reg latch,
    output reg blank,
    output reg sclk_out,
    output reg [3:0] address
  );
  
  
  
  reg rst;
  
  wire [6-1:0] M_matrixwriter_col_index;
  wire [4-1:0] M_matrixwriter_row_index;
  wire [1-1:0] M_matrixwriter_red0;
  wire [1-1:0] M_matrixwriter_green0;
  wire [1-1:0] M_matrixwriter_blue0;
  wire [1-1:0] M_matrixwriter_red1;
  wire [1-1:0] M_matrixwriter_green1;
  wire [1-1:0] M_matrixwriter_blue1;
  wire [1-1:0] M_matrixwriter_latch;
  wire [1-1:0] M_matrixwriter_blank;
  wire [1-1:0] M_matrixwriter_sclk_out;
  wire [4-1:0] M_matrixwriter_address;
  wire [16-1:0] M_matrixwriter_debug;
  reg [6-1:0] M_matrixwriter_data;
  matrix_writer_1 matrixwriter (
    .clk(clk),
    .rst(rst),
    .data(M_matrixwriter_data),
    .col_index(M_matrixwriter_col_index),
    .row_index(M_matrixwriter_row_index),
    .red0(M_matrixwriter_red0),
    .green0(M_matrixwriter_green0),
    .blue0(M_matrixwriter_blue0),
    .red1(M_matrixwriter_red1),
    .green1(M_matrixwriter_green1),
    .blue1(M_matrixwriter_blue1),
    .latch(M_matrixwriter_latch),
    .blank(M_matrixwriter_blank),
    .sclk_out(M_matrixwriter_sclk_out),
    .address(M_matrixwriter_address),
    .debug(M_matrixwriter_debug)
  );
  
  wire [4-1:0] M_ramwriter_row_address_top;
  wire [6-1:0] M_ramwriter_col_address_top;
  wire [1-1:0] M_ramwriter_we_top;
  wire [3-1:0] M_ramwriter_wd_top;
  wire [4-1:0] M_ramwriter_row_address_btm;
  wire [6-1:0] M_ramwriter_col_address_btm;
  wire [1-1:0] M_ramwriter_we_btm;
  wire [3-1:0] M_ramwriter_wd_btm;
  wire [1-1:0] M_ramwriter_ready;
  reg [48-1:0] M_ramwriter_new_data;
  reg [5-1:0] M_ramwriter_button_clicked;
  reg [160-1:0] M_ramwriter_out;
  matrix_ram_writer_2 ramwriter (
    .clk(clk),
    .rst(rst),
    .new_data(M_ramwriter_new_data),
    .button_clicked(M_ramwriter_button_clicked),
    .out(M_ramwriter_out),
    .row_address_top(M_ramwriter_row_address_top),
    .col_address_top(M_ramwriter_col_address_top),
    .we_top(M_ramwriter_we_top),
    .wd_top(M_ramwriter_wd_top),
    .row_address_btm(M_ramwriter_row_address_btm),
    .col_address_btm(M_ramwriter_col_address_btm),
    .we_btm(M_ramwriter_we_btm),
    .wd_btm(M_ramwriter_wd_btm),
    .ready(M_ramwriter_ready)
  );
  
  wire [3-1:0] M_matrixram_top_out;
  wire [3-1:0] M_matrixram_bottom_out;
  reg [4-1:0] M_matrixram_row_address;
  reg [6-1:0] M_matrixram_col_address;
  reg [4-1:0] M_matrixram_row_address_top;
  reg [6-1:0] M_matrixram_col_address_top;
  reg [1-1:0] M_matrixram_we_top;
  reg [3-1:0] M_matrixram_wd_top;
  reg [4-1:0] M_matrixram_row_address_btm;
  reg [6-1:0] M_matrixram_col_address_btm;
  reg [1-1:0] M_matrixram_we_btm;
  reg [3-1:0] M_matrixram_wd_btm;
  reg [1-1:0] M_matrixram_ready;
  matrix_ram_3 matrixram (
    .clk(clk),
    .rst(rst),
    .row_address(M_matrixram_row_address),
    .col_address(M_matrixram_col_address),
    .row_address_top(M_matrixram_row_address_top),
    .col_address_top(M_matrixram_col_address_top),
    .we_top(M_matrixram_we_top),
    .wd_top(M_matrixram_wd_top),
    .row_address_btm(M_matrixram_row_address_btm),
    .col_address_btm(M_matrixram_col_address_btm),
    .we_btm(M_matrixram_we_btm),
    .wd_btm(M_matrixram_wd_btm),
    .ready(M_matrixram_ready),
    .top_out(M_matrixram_top_out),
    .bottom_out(M_matrixram_bottom_out)
  );
  
  reg [7:0] M_row_index_d, M_row_index_q = 1'h0;
  
  reg [7:0] M_col_index_d, M_col_index_q = 1'h0;
  
  wire [16-1:0] M_cpu_timer;
  wire [16-1:0] M_cpu_score;
  wire [160-1:0] M_cpu_out;
  reg [1-1:0] M_cpu_reset_button;
  reg [1-1:0] M_cpu_start_button;
  reg [1-1:0] M_cpu_left;
  reg [1-1:0] M_cpu_right;
  reg [1-1:0] M_cpu_up;
  reg [1-1:0] M_cpu_down;
  full_circuit_4 cpu (
    .clk(clk),
    .rst(rst),
    .reset_button(M_cpu_reset_button),
    .start_button(M_cpu_start_button),
    .left(M_cpu_left),
    .right(M_cpu_right),
    .up(M_cpu_up),
    .down(M_cpu_down),
    .timer(M_cpu_timer),
    .score(M_cpu_score),
    .out(M_cpu_out)
  );
  
  wire [7-1:0] M_seg_seg;
  wire [4-1:0] M_seg_sel;
  reg [16-1:0] M_seg_values;
  multi_seven_seg_5 seg (
    .clk(clk),
    .rst(rst),
    .values(M_seg_values),
    .seg(M_seg_seg),
    .sel(M_seg_sel)
  );
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_6 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [(3'h5+0)-1:0] M_buttoncond_out;
  reg [(3'h5+0)-1:0] M_buttoncond_in;
  
  genvar GEN_buttoncond0;
  generate
  for (GEN_buttoncond0=0;GEN_buttoncond0<3'h5;GEN_buttoncond0=GEN_buttoncond0+1) begin: buttoncond_gen_0
    button_conditioner_7 buttoncond (
      .clk(clk),
      .in(M_buttoncond_in[GEN_buttoncond0*(1)+(1)-1-:(1)]),
      .out(M_buttoncond_out[GEN_buttoncond0*(1)+(1)-1-:(1)])
    );
  end
  endgenerate
  wire [(3'h5+0)-1:0] M_buttondetector_out;
  reg [(3'h5+0)-1:0] M_buttondetector_in;
  
  genvar GEN_buttondetector0;
  generate
  for (GEN_buttondetector0=0;GEN_buttondetector0<3'h5;GEN_buttondetector0=GEN_buttondetector0+1) begin: buttondetector_gen_0
    edge_detector_8 buttondetector (
      .clk(clk),
      .in(M_buttondetector_in[GEN_buttondetector0*(1)+(1)-1-:(1)]),
      .out(M_buttondetector_out[GEN_buttondetector0*(1)+(1)-1-:(1)])
    );
  end
  endgenerate
  
  always @* begin
    M_col_index_d = M_col_index_q;
    M_row_index_d = M_row_index_q;
    
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    usb_tx = usb_rx;
    led = 8'h00;
    io_led = 24'h000000;
    io_seg = 8'hff;
    io_sel = 4'hf;
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    usb_tx = usb_rx;
    led = 8'h00;
    io_led = 24'h000000;
    io_seg = 8'hff;
    io_sel = 4'hf;
    M_buttoncond_in = io_button;
    M_buttondetector_in = M_buttoncond_out;
    M_cpu_up = M_buttondetector_out[0+0-:1];
    M_cpu_down = M_buttondetector_out[2+0-:1];
    M_cpu_left = M_buttondetector_out[3+0-:1];
    M_cpu_right = M_buttondetector_out[4+0-:1];
    M_cpu_start_button = M_buttondetector_out[1+0-:1];
    M_cpu_reset_button = io_dip[0+0+0-:1];
    M_seg_values = {M_cpu_out[16+0+3-:4], M_cpu_out[32+0+3-:4], M_cpu_out[48+0+3-:4], M_cpu_timer[0+3-:4]};
    io_seg = ~M_seg_seg;
    io_sel = ~M_seg_sel;
    io_led[0+15-:16] = M_cpu_score;
    M_ramwriter_out = M_cpu_out;
    M_ramwriter_button_clicked = M_buttondetector_out;
    M_ramwriter_new_data = {{io_dip[16+7-:8], io_dip[16+7-:8]}, {io_dip[8+7-:8], io_dip[8+7-:8]}, {io_dip[0+7-:8], io_dip[0+7-:8]}};
    M_matrixram_row_address_top = M_ramwriter_row_address_top;
    M_matrixram_col_address_top = M_ramwriter_col_address_top;
    M_matrixram_we_top = M_ramwriter_we_top;
    M_matrixram_wd_top = M_ramwriter_wd_top;
    M_matrixram_row_address_btm = M_ramwriter_row_address_btm;
    M_matrixram_col_address_btm = M_ramwriter_col_address_btm;
    M_matrixram_we_btm = M_ramwriter_we_btm;
    M_matrixram_wd_btm = M_ramwriter_wd_btm;
    M_matrixram_ready = M_ramwriter_ready;
    M_matrixram_row_address = M_matrixwriter_row_index;
    M_matrixram_col_address = M_matrixwriter_col_index;
    M_matrixwriter_data = {M_matrixram_bottom_out, M_matrixram_top_out};
    red0 = M_matrixwriter_red0;
    red1 = M_matrixwriter_red1;
    green0 = M_matrixwriter_green0;
    green1 = M_matrixwriter_green1;
    blue0 = M_matrixwriter_blue0;
    blue1 = M_matrixwriter_blue1;
    latch = M_matrixwriter_latch;
    sclk_out = M_matrixwriter_sclk_out;
    blank = M_matrixwriter_blank;
    address = M_matrixwriter_address;
    if (M_matrixwriter_row_index != 1'h0) begin
      M_row_index_d = M_matrixwriter_row_index;
    end
    if (M_matrixwriter_col_index != 1'h0) begin
      M_col_index_d = M_matrixwriter_col_index;
    end
  end
  
  always @(posedge clk) begin
    M_row_index_q <= M_row_index_d;
  end
  
  
  always @(posedge clk) begin
    M_col_index_q <= M_col_index_d;
  end
  
endmodule
