/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module boolean_33 (
    input [15:0] a,
    input [15:0] b,
    input [3:0] alufn,
    output reg [15:0] out
  );
  
  
  
  reg [15:0] temp;
  
  always @* begin
    
    case (alufn)
      4'h8: begin
        temp = a & b;
      end
      4'he: begin
        temp = a | b;
      end
      4'h6: begin
        temp = a ^ b;
      end
      4'ha: begin
        temp = a;
      end
      4'hc: begin
        temp = b;
      end
      4'h7: begin
        temp = ~(a & b);
      end
      4'h1: begin
        temp = ~(a | b);
      end
      4'h9: begin
        temp = ~(a ^ b);
      end
      default: begin
        temp = 16'h0000;
      end
    endcase
    out = temp;
  end
endmodule
