/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module regfile_15 (
    input clk,
    input [3:0] ra,
    input [3:0] rb,
    input [3:0] rc,
    input we,
    input [15:0] write_data,
    output reg [15:0] ra_data,
    output reg [15:0] rb_data,
    output reg [15:0] score,
    output reg [15:0] timer,
    output reg [159:0] out
  );
  
  
  
  reg [255:0] M_registers_d, M_registers_q = 1'h0;
  
  always @* begin
    M_registers_d = M_registers_q;
    
    ra_data = M_registers_q[(ra)*16+15-:16];
    rb_data = M_registers_q[(rb)*16+15-:16];
    score = M_registers_q[160+15-:16];
    timer = M_registers_q[0+15-:16];
    out[0+15-:16] = M_registers_q[176+15-:16];
    out[16+143-:144] = M_registers_q[16+143-:144];
    if (we) begin
      M_registers_d[(rc)*16+15-:16] = write_data;
    end
  end
  
  always @(posedge clk) begin
    M_registers_q <= M_registers_d;
  end
  
endmodule
