/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module wasel_12 (
    input [3:0] rc,
    input [3:0] rb_data,
    input wasel,
    output reg [3:0] out
  );
  
  
  
  always @* begin
    if (wasel == 1'h0) begin
      out = rc;
    end else begin
      out = rb_data;
    end
  end
endmodule
