/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module wdsel_21 (
    input [15:0] alu,
    input [1:0] wdsel,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    
    case (wdsel)
      2'h1: begin
        out = 16'h0000;
      end
      2'h2: begin
        out = 16'h0001;
      end
      2'h3: begin
        out = 16'h0004;
      end
      default: begin
        out = alu;
      end
    endcase
  end
endmodule
