/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module booleanTester_10 (
    input clk,
    input rst,
    input start,
    output reg [1:0] status,
    output reg [15:0] out
  );
  
  
  
  reg [3:0] M_counter_d, M_counter_q = 1'h0;
  
  
  localparam IDLE_state = 2'd0;
  localparam TEST_state = 2'd1;
  localparam PASS_state = 2'd2;
  localparam FAIL_state = 2'd3;
  
  reg [1:0] M_state_d, M_state_q = IDLE_state;
  
  wire [16-1:0] M_bool_out;
  reg [16-1:0] M_bool_a;
  reg [16-1:0] M_bool_b;
  reg [4-1:0] M_bool_alufn;
  boolean_21 bool (
    .a(M_bool_a),
    .b(M_bool_b),
    .alufn(M_bool_alufn),
    .out(M_bool_out)
  );
  
  always @* begin
    M_state_d = M_state_q;
    M_counter_d = M_counter_q;
    
    status = 1'h0;
    M_bool_a = 1'h0;
    M_bool_b = 1'h0;
    M_bool_alufn = 1'h0;
    if (start == 1'h0) begin
      M_state_d = IDLE_state;
    end
    
    case (M_state_q)
      IDLE_state: begin
        status = 1'h0;
        if (start == 1'h1) begin
          M_state_d = TEST_state;
        end
      end
      TEST_state: begin
        
        case (M_counter_q)
          1'h1: begin
            M_bool_alufn = 4'h8;
            M_bool_a = 16'h002a;
            M_bool_b = 16'h0018;
            if (M_bool_out != 16'h0008) begin
              M_state_d = FAIL_state;
            end
          end
          2'h2: begin
            M_bool_alufn = 4'he;
            M_bool_a = 16'h002a;
            M_bool_b = 16'h0018;
            if (M_bool_out != 16'h003a) begin
              M_state_d = FAIL_state;
            end
          end
          2'h3: begin
            M_bool_alufn = 4'h6;
            M_bool_a = 16'h002a;
            M_bool_b = 16'h0018;
            if (M_bool_out != 16'h0032) begin
              M_state_d = FAIL_state;
            end
          end
          3'h4: begin
            M_bool_alufn = 4'ha;
            M_bool_a = 16'h002a;
            M_bool_b = 16'h0018;
            if (M_bool_out != 16'h002a) begin
              M_state_d = FAIL_state;
            end
          end
          3'h5: begin
            M_bool_alufn = 4'hc;
            M_bool_a = 16'h002a;
            M_bool_b = 16'h0018;
            if (M_bool_out != 16'h0018) begin
              M_state_d = FAIL_state;
            end
          end
          3'h6: begin
            M_bool_alufn = 4'h7;
            M_bool_a = 16'h002a;
            M_bool_b = 16'h0018;
            if (M_bool_out != 16'hfff7) begin
              M_state_d = FAIL_state;
            end
          end
          3'h7: begin
            M_bool_alufn = 4'h1;
            M_bool_a = 16'h002a;
            M_bool_b = 16'h0018;
            if (M_bool_out != 16'hffc5) begin
              M_state_d = FAIL_state;
            end
          end
          4'h8: begin
            M_bool_alufn = 4'h9;
            M_bool_a = 16'h002a;
            M_bool_b = 16'h0018;
            if (M_bool_out != 16'hffcd) begin
              M_state_d = FAIL_state;
            end
          end
          4'h9: begin
            M_state_d = PASS_state;
          end
        endcase
      end
      PASS_state: begin
        status = 1'h1;
      end
      FAIL_state: begin
        status = 2'h2;
      end
    endcase
    M_counter_d = M_counter_q + 1'h1;
    out = M_bool_out;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_counter_q <= 1'h0;
    end else begin
      M_counter_q <= M_counter_d;
    end
  end
  
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_state_q <= 1'h0;
    end else begin
      M_state_q <= M_state_d;
    end
  end
  
endmodule
