/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module comparator_18 (
    input [5:0] alufn,
    input z,
    input n,
    input v,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    out[1+14-:15] = 1'h0;
    
    case (alufn[1+1-:2])
      default: begin
        out[0+0-:1] = 1'h0;
      end
      2'h2: begin
        out[0+0-:1] = n ^ v;
      end
      2'h1: begin
        out[0+0-:1] = z;
      end
      2'h3: begin
        out[0+0-:1] = (n ^ v) | z;
      end
    endcase
  end
endmodule
