/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module arrow_rom_9 (
    input [3:0] choice,
    output reg [191:0] arrow,
    output reg [2:0] colour
  );
  
  
  
  localparam COLOUR = 24'haf1538;
  
  localparam RIGHT_ARROW = 192'h00000000000000000000024a20b1cc1cb1ca1c91c818b14a;
  
  localparam LEFT_ARROW = 192'h00000000000000000000024a2091cc1cb1ca1c91c818914a;
  
  localparam UP_ARROW = 192'h00000000000000000000024a20a1ca18a14a18918b1c81cc;
  
  localparam DOWN_ARROW = 192'h00000000000000000000020920b1c81cc24a20a1ca18a14a;
  
  always @* begin
    
    case (choice)
      1'h0: begin
        arrow = 192'h00000000000000000000024a20b1cc1cb1ca1c91c818b14a;
        colour = 3'h1;
      end
      1'h1: begin
        arrow = 192'h00000000000000000000024a2091cc1cb1ca1c91c818914a;
        colour = 3'h7;
      end
      2'h2: begin
        arrow = 192'h00000000000000000000024a20b1cc1cb1ca1c91c818b14a;
        colour = 3'h7;
      end
      2'h3: begin
        arrow = 192'h00000000000000000000024a20a1ca18a14a18918b1c81cc;
        colour = 3'h7;
      end
      3'h4: begin
        arrow = 192'h00000000000000000000020920b1c81cc24a20a1ca18a14a;
        colour = 3'h7;
      end
      3'h5: begin
        arrow = 192'h00000000000000000000024a2091cc1cb1ca1c91c818914a;
        colour = 3'h2;
      end
      3'h6: begin
        arrow = 192'h00000000000000000000024a20b1cc1cb1ca1c91c818b14a;
        colour = 3'h2;
      end
      3'h7: begin
        arrow = 192'h00000000000000000000024a20a1ca18a14a18918b1c81cc;
        colour = 3'h2;
      end
      4'h8: begin
        arrow = 192'h00000000000000000000020920b1c81cc24a20a1ca18a14a;
        colour = 3'h2;
      end
      default: begin
        arrow = 192'h00000000000000000000024a20a1ca18a14a18918b1c81cc;
        colour = 3'h6;
      end
    endcase
  end
endmodule
