/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module bsel_15 (
    input [15:0] rb_data,
    input [2:0] bsel,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    out = 1'h0;
    
    case (bsel)
      3'h0: begin
        out = rb_data;
      end
      3'h1: begin
        out = 16'h0001;
      end
      3'h2: begin
        out = 16'h0002;
      end
      3'h3: begin
        out = 16'h0003;
      end
      3'h4: begin
        out = 16'h0004;
      end
      3'h5: begin
        out = 16'h0009;
      end
      3'h6: begin
        out = 16'h0000;
      end
      default: begin
        out = 1'h0;
      end
    endcase
  end
endmodule
