/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module auto_tester_2 (
    input clk,
    input rst,
    input [2:0] button,
    input [0:0] inv,
    output reg [2:0] out_state,
    output reg [1:0] out_status,
    output reg [15:0] out_led
  );
  
  
  
  wire [24-1:0] M_test_adder_io_led;
  wire [2-1:0] M_test_adder_status;
  wire [16-1:0] M_test_adder_out;
  reg [1-1:0] M_test_adder_start;
  reg [1-1:0] M_test_adder_inv;
  adderTester_8 test_adder (
    .clk(clk),
    .rst(rst),
    .start(M_test_adder_start),
    .inv(M_test_adder_inv),
    .io_led(M_test_adder_io_led),
    .status(M_test_adder_status),
    .out(M_test_adder_out)
  );
  
  wire [2-1:0] M_test_compare_status;
  wire [16-1:0] M_test_compare_out;
  reg [1-1:0] M_test_compare_start;
  comparatorTester_9 test_compare (
    .clk(clk),
    .rst(rst),
    .start(M_test_compare_start),
    .status(M_test_compare_status),
    .out(M_test_compare_out)
  );
  
  wire [2-1:0] M_test_boole_status;
  wire [16-1:0] M_test_boole_out;
  reg [1-1:0] M_test_boole_start;
  booleanTester_10 test_boole (
    .clk(clk),
    .rst(rst),
    .start(M_test_boole_start),
    .status(M_test_boole_status),
    .out(M_test_boole_out)
  );
  
  wire [2-1:0] M_test_shifter_status;
  wire [16-1:0] M_test_shifter_out;
  reg [1-1:0] M_test_shifter_start;
  shifterTester_11 test_shifter (
    .clk(clk),
    .rst(rst),
    .start(M_test_shifter_start),
    .status(M_test_shifter_status),
    .out(M_test_shifter_out)
  );
  
  wire [2-1:0] M_test_multiply_status;
  wire [16-1:0] M_test_multiply_out;
  reg [1-1:0] M_test_multiply_start;
  multiplierTester_12 test_multiply (
    .clk(clk),
    .rst(rst),
    .start(M_test_multiply_start),
    .status(M_test_multiply_status),
    .out(M_test_multiply_out)
  );
  
  wire [2-1:0] M_test_error_status;
  reg [1-1:0] M_test_error_start;
  errorTester_13 test_error (
    .clk(clk),
    .rst(rst),
    .start(M_test_error_start),
    .status(M_test_error_status)
  );
  
  
  localparam IDLE_state = 3'd0;
  localparam ADDER_state = 3'd1;
  localparam COMPARATOR_state = 3'd2;
  localparam BOOLEAN_state = 3'd3;
  localparam SHIFTER_state = 3'd4;
  localparam MULTIPLIER_state = 3'd5;
  localparam ERROR_state = 3'd6;
  
  reg [2:0] M_state_d, M_state_q = IDLE_state;
  
  always @* begin
    M_state_d = M_state_q;
    
    M_test_adder_start = 1'h0;
    M_test_adder_inv = inv;
    M_test_compare_start = 1'h0;
    M_test_boole_start = 1'h0;
    M_test_shifter_start = 1'h0;
    M_test_multiply_start = 1'h0;
    M_test_error_start = 1'h0;
    out_status = 2'h0;
    out_state = M_state_q;
    out_led = 16'h0000;
    
    case (M_state_q)
      IDLE_state: begin
        out_status = 2'h0;
        if (button[0+0-:1]) begin
          M_state_d = ERROR_state;
        end else begin
          if (button[1+0-:1]) begin
            M_state_d = M_state_q + 1'h1;
          end
        end
      end
      ADDER_state: begin
        M_test_adder_start = 1'h1;
        M_test_adder_inv = inv;
        out_status = M_test_adder_status;
        out_led = M_test_adder_out;
        if (button[0+0-:1]) begin
          M_state_d = M_state_q - 1'h1;
        end else begin
          if (button[1+0-:1]) begin
            M_state_d = M_state_q + 1'h1;
          end
        end
      end
      COMPARATOR_state: begin
        M_test_compare_start = 1'h1;
        out_status = M_test_compare_status;
        out_led = M_test_compare_out;
        if (button[0+0-:1]) begin
          M_state_d = M_state_q - 1'h1;
        end else begin
          if (button[1+0-:1]) begin
            M_state_d = M_state_q + 1'h1;
          end
        end
      end
      BOOLEAN_state: begin
        M_test_boole_start = 1'h1;
        out_status = M_test_boole_status;
        out_led = M_test_boole_out;
        if (button[0+0-:1]) begin
          M_state_d = M_state_q - 1'h1;
        end else begin
          if (button[1+0-:1]) begin
            M_state_d = M_state_q + 1'h1;
          end
        end
      end
      SHIFTER_state: begin
        M_test_shifter_start = 1'h1;
        out_status = M_test_shifter_status;
        out_led = M_test_shifter_out;
        if (button[0+0-:1]) begin
          M_state_d = M_state_q - 1'h1;
        end else begin
          if (button[1+0-:1]) begin
            M_state_d = M_state_q + 1'h1;
          end
        end
      end
      MULTIPLIER_state: begin
        M_test_multiply_start = 1'h1;
        out_status = M_test_multiply_status;
        out_led = M_test_multiply_out;
        if (button[0+0-:1]) begin
          M_state_d = M_state_q - 1'h1;
        end else begin
          if (button[1+0-:1]) begin
            M_state_d = M_state_q + 1'h1;
          end
        end
      end
      ERROR_state: begin
        M_test_error_start = 1'h1;
        out_status = M_test_error_status;
        if (button[0+0-:1]) begin
          M_state_d = M_state_q - 1'h1;
        end else begin
          if (button[1+0-:1]) begin
            M_state_d = IDLE_state;
          end
        end
      end
    endcase
    if (button[2+0-:1]) begin
      M_state_d = IDLE_state;
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_state_q <= 1'h0;
    end else begin
      M_state_q <= M_state_d;
    end
  end
  
endmodule
