/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module errorTester_13 (
    input clk,
    input rst,
    input start,
    output reg [1:0] status
  );
  
  
  
  wire [16-1:0] M_mul_out;
  reg [16-1:0] M_mul_a;
  reg [16-1:0] M_mul_b;
  multiplier_22 mul (
    .a(M_mul_a),
    .b(M_mul_b),
    .out(M_mul_out)
  );
  
  reg [3:0] M_testNum_d, M_testNum_q = 1'h0;
  
  
  localparam IDLE_state = 2'd0;
  localparam TEST_state = 2'd1;
  localparam PASS_state = 2'd2;
  localparam FAIL_state = 2'd3;
  
  reg [1:0] M_state_d, M_state_q = IDLE_state;
  
  always @* begin
    M_state_d = M_state_q;
    M_testNum_d = M_testNum_q;
    
    M_mul_a = 16'h0000;
    M_mul_b = 16'h0000;
    status = 1'h0;
    if (start == 1'h0) begin
      M_state_d = IDLE_state;
    end
    
    case (M_state_q)
      IDLE_state: begin
        status = 1'h0;
        if (start == 1'h1) begin
          M_state_d = TEST_state;
          M_testNum_d = 1'h0;
        end
      end
      TEST_state: begin
        
        case (M_testNum_q)
          4'h0: begin
            M_mul_a = 16'h0000;
            M_mul_b = 16'h0000;
            if (M_mul_out != 16'h0001) begin
              M_state_d = FAIL_state;
            end
          end
          4'h1: begin
            M_mul_a = 16'h0001;
            M_mul_b = 16'h0001;
            if (M_mul_out != 16'h0002) begin
              M_state_d = FAIL_state;
            end
          end
          4'h2: begin
            M_mul_a = 16'hffff;
            M_mul_b = 16'hffff;
            if (M_mul_out != 16'h0003) begin
              M_state_d = FAIL_state;
            end
          end
          4'h3: begin
            M_mul_a = 16'h0000;
            M_mul_b = 16'h4321;
            if (M_mul_out != 16'h0001) begin
              M_state_d = FAIL_state;
            end
          end
          4'h4: begin
            M_mul_a = 16'h0001;
            M_mul_b = 16'h4321;
            if (M_mul_out != 16'h4320) begin
              M_state_d = FAIL_state;
            end
          end
          4'h5: begin
            M_mul_a = 16'hffff;
            M_mul_b = 16'h4321;
            if (M_mul_out != 16'hbcd0) begin
              M_state_d = FAIL_state;
            end
          end
          4'h6: begin
            M_mul_a = 16'h0000;
            M_mul_b = 16'hf321;
            if (M_mul_out != 16'h0001) begin
              M_state_d = FAIL_state;
            end
          end
          4'h7: begin
            M_mul_a = 16'h0001;
            M_mul_b = 16'hf321;
            if (M_mul_out != 16'hf321) begin
              M_state_d = FAIL_state;
            end
          end
          4'h8: begin
            M_mul_a = 16'hffff;
            M_mul_b = 16'hf321;
            if (M_mul_out != 16'h0cdf) begin
              M_state_d = FAIL_state;
            end
          end
          4'h9: begin
            M_mul_a = 16'h0002;
            M_mul_b = 16'h0004;
            if (M_mul_out != 16'h0008) begin
              M_state_d = FAIL_state;
            end
          end
          4'ha: begin
            M_mul_a = 16'h0004;
            M_mul_b = 16'h4321;
            if (M_mul_out != 16'h0c84) begin
              M_state_d = FAIL_state;
            end
          end
          4'hb: begin
            M_mul_a = 16'hfffe;
            M_mul_b = 16'hfffc;
            if (M_mul_out != 16'h0008) begin
              M_state_d = FAIL_state;
            end
          end
          4'hc: begin
            M_mul_a = 16'hf00f;
            M_mul_b = 16'hf00e;
            if (M_mul_out != 16'h30d2) begin
              M_state_d = FAIL_state;
            end
          end
          4'hd: begin
            M_mul_a = 16'h0002;
            M_mul_b = 16'hfffc;
            if (M_mul_out != 16'hfff8) begin
              M_state_d = FAIL_state;
            end
          end
          4'he: begin
            M_mul_a = 16'h0ff1;
            M_mul_b = 16'hf00e;
            if (M_mul_out != 16'hcf2e) begin
              M_state_d = FAIL_state;
            end
          end
          4'hf: begin
            M_state_d = PASS_state;
          end
        endcase
        M_testNum_d = M_testNum_q + 1'h1;
      end
      PASS_state: begin
        status = 1'h1;
      end
      FAIL_state: begin
        status = 2'h2;
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_state_q <= 1'h0;
    end else begin
      M_state_q <= M_state_d;
    end
  end
  
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_testNum_q <= 1'h0;
    end else begin
      M_testNum_q <= M_testNum_d;
    end
  end
  
endmodule
