/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     NUM_CASES = 15
     DIGITS = 4
     DIV = 27
*/
module test_case_enum_23 (
    input clk,
    input rst,
    output reg [3:0] sel
  );
  
  localparam NUM_CASES = 4'hf;
  localparam DIGITS = 3'h4;
  localparam DIV = 5'h1b;
  
  
  wire [4-1:0] M_ctr_value;
  counter_24 ctr (
    .clk(clk),
    .rst(rst),
    .value(M_ctr_value)
  );
  
  always @* begin
    sel = M_ctr_value;
  end
endmodule
